"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.countrys = void 0;
exports.countrys = [
    { id: 144, text: "Afganistán", code: "AF" },
    { id: 114, text: "Albania", code: "AL" },
    { id: 18, text: "Alemania", code: "DE" },
    { id: 98, text: "Argelia", code: "DZ" },
    { id: 145, text: "Andorra", code: "AD" },
    { id: 119, text: "Angola", code: "AO" },
    { id: 4, text: "Anguila", code: "AI" },
    { id: 147, text: "Antigua y Barbuda", code: "AG" },
    { id: 207, text: "Antillas Holandesas", code: "AN" },
    { id: 91, text: "Arabia Saudita", code: "SA" },
    { id: 5, text: "Argentina", code: "AR" },
    { id: 6, text: "Armenia", code: "AM" },
    { id: 142, text: "Aruba", code: "AW" },
    { id: 1, text: "Australia", code: "AU" },
    { id: 2, text: "Austria", code: "AT" },
    { id: 3, text: "Azerbaiyán", code: "AZ" },
    { id: 80, text: "Bahamas", code: "BS" },
    { id: 127, text: "Baréin", code: "BH" },
    { id: 149, text: "Bangladesh", code: "BD" },
    { id: 128, text: "Barbados", code: "BB" },
    { id: 9, text: "Bélgica", code: "BE" },
    { id: 8, text: "Belice", code: "BZ" },
    { id: 151, text: "Benín", code: "BJ" },
    { id: 10, text: "Bermudas", code: "BM" },
    { id: 7, text: "Bielorrusia", code: "BY" },
    { id: 123, text: "Bolivia", code: "BO" },
    { id: 79, text: "Bosnia y Herzegovina", code: "BA" },
    { id: 100, text: "Botsuana", code: "BW" },
    { id: 12, text: "Brasil", code: "BR" },
    { id: 155, text: "Brunéi", code: "BN" },
    { id: 11, text: "Bulgaria", code: "BG" },
    { id: 156, text: "Burkina Faso", code: "BF" },
    { id: 157, text: "Burundi", code: "BI" },
    { id: 152, text: "Bután", code: "BT" },
    { id: 159, text: "Cabo Verde", code: "CV" },
    { id: 158, text: "Camboya", code: "KH" },
    { id: 31, text: "Camerún", code: "CM" },
    { id: 32, text: "Canadá", code: "CA" },
    { id: 130, text: "Chad", code: "TD" },
    { id: 81, text: "Chile", code: "CL" },
    { id: 35, text: "China", code: "CN" },
    { id: 33, text: "Chipre", code: "CY" },
    { id: 82, text: "Colombia", code: "CO" },
    { id: 164, text: "Comores", code: "KM" },
    { id: 112, text: "Congo (Brazzaville)", code: "CG" },
    { id: 165, text: "Congo (Kinshasa)", code: "CD" },
    { id: 166, text: "Cook, Islas", code: "CK" },
    { id: 84, text: "Corea del Norte", code: "KP" },
    { id: 69, text: "Corea del Sur", code: "KR" },
    { id: 168, text: "Costa de Marfil", code: "CI" },
    { id: 36, text: "Costa Rica", code: "CR" },
    { id: 71, text: "Croacia", code: "HR" },
    { id: 113, text: "Cuba", code: "CU" },
    { id: 22, text: "Dinamarca", code: "DK" },
    { id: 169, text: "Djibouti, Yibuti", code: "DJ" },
    { id: 103, text: "Ecuador", code: "EC" },
    { id: 23, text: "Egipto", code: "EG" },
    { id: 51, text: "El Salvador", code: "SV" },
    { id: 93, text: "Emiratos Árabes Unidos", code: "AE" },
    { id: 173, text: "Eritrea", code: "ER" },
    { id: 52, text: "Eslovaquia", code: "SK" },
    { id: 53, text: "Eslovenia", code: "SI" },
    { id: 28, text: "España", code: "ES" },
    { id: 55, text: "Estados Unidos", code: "US" },
    { id: 68, text: "Estonia", code: "EE" },
    { id: 121, text: "Etiopía", code: "ET" },
    { id: 175, text: "Feroe, Islas", code: "FO" },
    { id: 90, text: "Filipinas", code: "PH" },
    { id: 63, text: "Finlandia", code: "FI" },
    { id: 176, text: "Fiyi", code: "FJ" },
    { id: 64, text: "Francia", code: "FR" },
    { id: 180, text: "Gabón", code: "GA" },
    { id: 181, text: "Gambia", code: "GM" },
    { id: 21, text: "Georgia", code: "GE" },
    { id: 105, text: "Ghana", code: "GH" },
    { id: 143, text: "Gibraltar", code: "GI" },
    { id: 184, text: "Granada", code: "GD" },
    { id: 20, text: "Grecia", code: "GR" },
    { id: 94, text: "Groenlandia", code: "GL" },
    { id: 17, text: "Guadalupe", code: "GP" },
    { id: 185, text: "Guatemala", code: "GT" },
    { id: 186, text: "Guernsey", code: "GG" },
    { id: 187, text: "Guinea", code: "GN" },
    { id: 172, text: "Guinea Ecuatorial", code: "GQ" },
    { id: 188, text: "Guinea-Bissau", code: "GW" },
    { id: 189, text: "Guyana", code: "GY" },
    { id: 16, text: "Haiti", code: "HT" },
    { id: 137, text: "Honduras", code: "HN" },
    { id: 73, text: "Hong Kong", code: "HK" },
    { id: 14, text: "Hungría", code: "HU" },
    { id: 25, text: "India", code: "IN" },
    { id: 74, text: "Indonesia", code: "ID" },
    { id: 140, text: "Irak", code: "IQ" },
    { id: 26, text: "Irán", code: "IR" },
    { id: 27, text: "Irlanda", code: "IE" },
    { id: 215, text: "Isla Pitcairn", code: "PN" },
    { id: 83, text: "Islandia", code: "IS" },
    { id: 228, text: "Islas Salomón", code: "SB" },
    { id: 58, text: "Islas Turcas y Caicos", code: "TC" },
    { id: 154, text: "Islas Vírgenes Británicas", code: "VG" },
    { id: 24, text: "Israel", code: "IL" },
    { id: 29, text: "Italia", code: "IT" },
    { id: 132, text: "Jamaica", code: "JM" },
    { id: 70, text: "Japón", code: "JP" },
    { id: 193, text: "Jersey", code: "JE" },
    { id: 75, text: "Jordania", code: "JO" },
    { id: 30, text: "Kazajstán", code: "KZ" },
    { id: 97, text: "Kenia", code: "KE" },
    { id: 34, text: "Kirguistán", code: "KG" },
    { id: 195, text: "Kiribati", code: "KI" },
    { id: 37, text: "Kuwait", code: "KW" },
    { id: 196, text: "Laos", code: "LA" },
    { id: 197, text: "Lesotho", code: "LS" },
    { id: 38, text: "Letonia", code: "LV" },
    { id: 99, text: "Líbano", code: "LB" },
    { id: 198, text: "Liberia", code: "LR" },
    { id: 39, text: "Libia", code: "LY" },
    { id: 126, text: "Liechtenstein", code: "LI" },
    { id: 40, text: "Lituania", code: "LT" },
    { id: 41, text: "Luxemburgo", code: "LU" },
    { id: 85, text: "Macedonia", code: "MK" },
    { id: 134, text: "Madagascar", code: "MG" },
    { id: 76, text: "Malasia", code: "MY" },
    { id: 125, text: "Malaui", code: "MW" },
    { id: 200, text: "Maldivas", code: "MV" },
    { id: 133, text: "Malí", code: "ML" },
    { id: 86, text: "Malta", code: "MT" },
    { id: 131, text: "Isla de Man", code: "IM" },
    { id: 104, text: "Marruecos", code: "MA" },
    { id: 201, text: "Martinica", code: "MQ" },
    { id: 202, text: "Mauricio", code: "MU" },
    { id: 108, text: "Mauritania", code: "MR" },
    { id: 42, text: "México", code: "MX" },
    { id: 43, text: "Moldavia", code: "MD" },
    { id: 44, text: "Mónaco", code: "MC" },
    { id: 139, text: "Mongolia", code: "MN" },
    { id: 117, text: "Mozambique", code: "MZ" },
    { id: 205, text: "Myanmar", code: "MM" },
    { id: 102, text: "Namibia", code: "NA" },
    { id: 206, text: "Nauru", code: "NR" },
    { id: 107, text: "Nepal", code: "NP" },
    { id: 209, text: "Nicaragua", code: "NI" },
    { id: 210, text: "Níger", code: "NE" },
    { id: 115, text: "Nigeria", code: "NG" },
    { id: 212, text: "Norfolk Island", code: "NF" },
    { id: 46, text: "Noruega", code: "NO" },
    { id: 208, text: "Nueva Caledonia", code: "NC" },
    { id: 45, text: "Nueva Zelanda", code: "NZ" },
    { id: 213, text: "Omán", code: "OM" },
    { id: 19, text: "Países Bajos, Holanda", code: "NL" },
    { id: 87, text: "Pakistán", code: "PK" },
    { id: 124, text: "Panamá", code: "PA" },
    { id: 88, text: "Papúa-Nueva Guinea", code: "PG" },
    { id: 110, text: "Paraguay", code: "PY" },
    { id: 89, text: "Perú", code: "PE" },
    { id: 178, text: "Polinesia Francesa", code: "PF" },
    { id: 47, text: "Polonia", code: "PL" },
    { id: 48, text: "Portugal", code: "PT" },
    { id: 246, text: "Puerto Rico", code: "PR" },
    { id: 216, text: "Qatar", code: "QA" },
    { id: 13, text: "Reino Unido", code: "GB" },
    { id: 65, text: "República Checa", code: "CZ" },
    { id: 138, text: "República Dominicana", code: "DO" },
    { id: 49, text: "Reunión", code: "RE" },
    { id: 217, text: "Ruanda", code: "RW" },
    { id: 72, text: "Rumanía", code: "RO" },
    { id: 50, text: "Rusia", code: "RU" },
    { id: 242, text: "Sáhara Occidental", code: "EH" },
    { id: 223, text: "Samoa", code: "WS" },
    { id: 219, text: "San Cristóbal y Nieves", code: "KN" },
    { id: 224, text: "San Marino", code: "SM" },
    { id: 221, text: "San Pedro y Miquelón", code: "PM" },
    { id: 225, text: "San Tomé y Príncipe", code: "ST" },
    { id: 222, text: "San Vicente y las Granadinas", code: "VC" },
    { id: 218, text: "Santa Elena", code: "SH" },
    { id: 220, text: "Santa Lucía", code: "LC" },
    { id: 135, text: "Senegal", code: "SN" },
    { id: 226, text: "Serbia y Montenegro", code: "CS" },
    { id: 109, text: "Seychelles", code: "SC" },
    { id: 227, text: "Sierra Leona", code: "SL" },
    { id: 77, text: "Singapur", code: "SG" },
    { id: 106, text: "Siria", code: "SY" },
    { id: 229, text: "Somalia", code: "SO" },
    { id: 120, text: "Sri Lanka", code: "LK" },
    { id: 141, text: "Sudáfrica", code: "ZA" },
    { id: 232, text: "Sudán", code: "SD" },
    { id: 67, text: "Suecia", code: "SE" },
    { id: 66, text: "Suiza", code: "CH" },
    { id: 54, text: "Surinam", code: "SR" },
    { id: 234, text: "Suazilandia", code: "SZ" },
    { id: 56, text: "Tayikistán", code: "TJ" },
    { id: 92, text: "Tailandia", code: "TH" },
    { id: 78, text: "Taiwán", code: "TW" },
    { id: 101, text: "Tanzania", code: "TZ" },
    { id: 171, text: "Timor Oriental", code: "TL" },
    { id: 136, text: "Togo", code: "TG" },
    { id: 235, text: "Tokelau", code: "TK" },
    { id: 236, text: "Tonga", code: "TO" },
    { id: 237, text: "Trinidad y Tobago", code: "TT" },
    { id: 122, text: "Túnez", code: "TN" },
    { id: 57, text: "Turkmenistán", code: "TM" },
    { id: 59, text: "Turquía", code: "TR" },
    { id: 239, text: "Tuvalu", code: "TV" },
    { id: 62, text: "Ucrania", code: "UA" },
    { id: 60, text: "Uganda", code: "UG" },
    { id: 111, text: "Uruguay", code: "UY" },
    { id: 61, text: "Uzbekistán", code: "UZ" },
    { id: 240, text: "Vanuatu", code: "VU" },
    { id: 95, text: "Venezuela", code: "VE" },
    { id: 15, text: "Vietnam", code: "VN" },
    { id: 241, text: "Wallis y Futuna", code: "WF" },
    { id: 243, text: "Yemen", code: "YE" },
    { id: 116, text: "Zambia", code: "ZM" },
    { id: 96, text: "Zimbabue", code: "ZW" },
    { id: 247, text: "Bonaire", code: "BON" },
    { id: 248, text: "Curazao", code: "CUR" },
];
//# sourceMappingURL=index.js.map